[theme]
file = "dracula-custom"

[icons]
name = "awesome5"
#theme = "nord-dark"
#icons = "awesome5"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]

[[block]]
block = "disk_space"
info_type = "used"
format = "{icon} {used}/{total}"
warning = 80
alert = 95

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}"

[[block]]
block = "sound"
max_vol = 100

[[block]]
block = "time"
